### ISSUE TITLE
Cuda out of Memory

### ISSUE THREAD

**Issue by klevin-ken** [HolmesShuan/Zero-shot-Style-Transfer-via-Attention-Rearrangement#2]
Hi !
My attempt to run the code failed duo out of memory while DDIM sampling.
I am using an RTX4090 with 24GB
What are the minimum specs to run? Thank you.

**Comment by HolmesShuan** [comment]
Thanks for your interest. We performed experiments using an NVIDIA Tesla V100 GPU with 32GB of memory and a PCIe 3.0 interface. If you experience an Out of Memory (OOM) issue, please consider downscaling to a lower resolution.

**Comment by klevin-ken** [comment]
Thanks!
