### ISSUE TITLE
Cannot Reproduce the result😱

### ISSUE THREAD

**Issue by BlueDyee** [HolmesShuan/Zero-shot-Style-Transfer-via-Attention-Rearrangement#3]
Hi,

First of all, thank you for your fantastic open-source project. I successfully managed to run the code after some troubleshooting, but I noticed that the style transfer effect seems quite minor.

Here are the changes I made:

1. Changed to revision fp16.
2. Adjusted the resolution to 512x512.

Could you please provide some guidance on how to enhance the style transfer effect?

Thank you!
![demo_0_demo_1](https://github.com/user-attachments/assets/024e4f78-9891-4784-aa80-b3dacd0630c2)
![demo_0_demo_0](https://github.com/user-attachments/assets/a8cf1e73-2162-44c6-806a-ab926e69f25e)

**Comment by HolmesShuan** [comment]
Thank you for your interest. I am sorry to hear that you are experiencing some issues. Have you tried reverting the setting of "Changed to revision fp16."?

**Comment by BlueDyee** [comment]
Thank you for your reply. Reverting the change to "revision fp16" does help.
![demo_0_demo_0](https://github.com/user-attachments/assets/7f316a3f-6b3d-4cca-a63b-54214c92a212)
![demo_0_demo_1](https://github.com/user-attachments/assets/27b3c8fe-a1ec-45eb-ab87-86e76fc14735)

It seems like the issue lies with the model rather than the precision?
 However, I'm still confused about how such a difference can exist between sd 1.5 and sd 1.5-fp16🤔.

BTW, for anyone facing the following error:
Unable to load weights from checkpoint file for './stable-diffusion-v1-5/unet/diffusion_pytorch_model.safetensors'

Just delete the .safetensors file, and Diffusers will automatically collect the .ckpt file.
